/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Description {
  versionMajor: number;
  versionMinor: number;
  versionPatch: number;
  moduleId: string;
  maxPcrs: number;
  lockedPcrs: Array<number>;
  digest: string;
}
export interface PcrDescription {
  lock: boolean;
  data: Buffer;
}
export declare function open(): number;
export declare function init(): number;
export declare function close(fd: number): void;
export declare function exit(fd: number): void;
export declare function extendPcr(
  fd: number,
  index: number,
  data: Buffer
): Buffer;
export declare function getPcrDescription(
  fd: number,
  index: number
): PcrDescription;
export declare function lockPcr(fd: number, index: number): void;
export declare function lockPcrs(fd: number, range: number): void;
export declare function getDescription(fd: number): Description;
export declare function getAttestationDoc(
  fd: number,
  userData?: Buffer | undefined | null,
  nonce?: Buffer | undefined | null,
  publicKey?: Buffer | undefined | null
): Buffer;
export declare function getRandom(fd: number): Buffer;
